# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-yaml
    - id: no-commit-to-branch
      args: ['--branch', 'master']
    - id: check-added-large-files
      args: ['--maxkb=500']

-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      exclude: precarious_papers/[a-z_/]+/tests/[a-z_]+.py$

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      exclude: precarious_papers/[a-z_/]+/tests/[a-z_]+.py$

-   repo: local
    hooks:
    - id: jupytext
      name: jupytext
      entry: jupytext --to py:percent
      files: .ipynb
      language: python
