2020-02-11 17:26:15  (rev 0)

2020-02-11 17:31:05  (rev 1)
    +_libgcc_mutex-0.1 (defaults/linux-64)
    +_tflow_select-2.3.0 (defaults/linux-64)
    +absl-py-0.8.1 (defaults/linux-64)
    +appdirs-1.4.3 (defaults/linux-64)
    +asn1crypto-1.3.0 (defaults/linux-64)
    +astor-0.8.0 (defaults/linux-64)
    +attrs-19.3.0 (defaults/noarch)
    +backcall-0.1.0 (defaults/linux-64)
    +black-19.3b0 (defaults/noarch)
    +blas-1.0 (defaults/linux-64)
    +bleach-3.1.0 (defaults/linux-64)
    +bokeh-1.4.0 (defaults/linux-64)
    +c-ares-1.15.0 (defaults/linux-64)
    +ca-certificates-2020.1.1 (defaults/linux-64)
    +certifi-2019.11.28 (defaults/linux-64)
    +cffi-1.14.0 (defaults/linux-64)
    +chardet-3.0.4 (defaults/linux-64)
    +click-7.0 (defaults/linux-64)
    +colorcet-2.0.2 (defaults/noarch)
    +cryptography-2.8 (defaults/linux-64)
    +cycler-0.10.0 (defaults/linux-64)
    +dbus-1.13.12 (defaults/linux-64)
    +decorator-4.4.1 (defaults/noarch)
    +defusedxml-0.6.0 (defaults/noarch)
    +entrypoints-0.3 (defaults/linux-64)
    +expat-2.2.6 (defaults/linux-64)
    +fontconfig-2.13.0 (defaults/linux-64)
    +freetype-2.9.1 (defaults/linux-64)
    +gast-0.2.2 (defaults/linux-64)
    +glib-2.63.1 (defaults/linux-64)
    +gmp-6.1.2 (defaults/linux-64)
    +google-pasta-0.1.8 (defaults/noarch)
    +grpcio-1.16.1 (defaults/linux-64)
    +gst-plugins-base-1.14.0 (defaults/linux-64)
    +gstreamer-1.14.0 (defaults/linux-64)
    +h5py-2.10.0 (defaults/linux-64)
    +hdf5-1.10.4 (defaults/linux-64)
    +holoviews-1.12.7 (defaults/noarch)
    +hvplot-0.5.2 (defaults/noarch)
    +icu-58.2 (defaults/linux-64)
    +idna-2.8 (defaults/linux-64)
    +importlib_metadata-1.5.0 (defaults/linux-64)
    +intel-openmp-2020.0 (defaults/linux-64)
    +ipykernel-5.1.4 (defaults/linux-64)
    +ipython-7.12.0 (defaults/linux-64)
    +ipython_genutils-0.2.0 (defaults/linux-64)
    +jedi-0.16.0 (defaults/linux-64)
    +jinja2-2.11.1 (defaults/noarch)
    +joblib-0.14.1 (defaults/noarch)
    +jpeg-9b (defaults/linux-64)
    +json5-0.9.1 (defaults/noarch)
    +jsonschema-3.2.0 (defaults/linux-64)
    +jupyter_client-5.3.4 (defaults/linux-64)
    +jupyter_core-4.6.1 (defaults/linux-64)
    +jupyterlab-1.2.6 (defaults/noarch)
    +jupyterlab_server-1.0.6 (defaults/noarch)
    +keras-applications-1.0.8 (defaults/noarch)
    +keras-preprocessing-1.1.0 (defaults/noarch)
    +kiwisolver-1.1.0 (defaults/linux-64)
    +ld_impl_linux-64-2.33.1 (defaults/linux-64)
    +libedit-3.1.20181209 (defaults/linux-64)
    +libffi-3.2.1 (defaults/linux-64)
    +libgcc-ng-9.1.0 (defaults/linux-64)
    +libgfortran-ng-7.3.0 (defaults/linux-64)
    +libpng-1.6.37 (defaults/linux-64)
    +libprotobuf-3.11.2 (defaults/linux-64)
    +libsodium-1.0.16 (defaults/linux-64)
    +libstdcxx-ng-9.1.0 (defaults/linux-64)
    +libtiff-4.1.0 (defaults/linux-64)
    +libuuid-1.0.3 (defaults/linux-64)
    +libxcb-1.13 (defaults/linux-64)
    +libxml2-2.9.9 (defaults/linux-64)
    +markdown-3.1.1 (defaults/linux-64)
    +markupsafe-1.1.1 (defaults/linux-64)
    +matplotlib-3.1.3 (defaults/linux-64)
    +matplotlib-base-3.1.3 (defaults/linux-64)
    +mistune-0.8.4 (defaults/linux-64)
    +mkl-2020.0 (defaults/linux-64)
    +mkl-service-2.3.0 (defaults/linux-64)
    +mkl_fft-1.0.15 (defaults/linux-64)
    +mkl_random-1.1.0 (defaults/linux-64)
    +nbconvert-5.6.1 (defaults/linux-64)
    +nbformat-5.0.4 (defaults/noarch)
    +ncurses-6.1 (defaults/linux-64)
    +neo4j-python-driver-1.7.1 (defaults/linux-64)
    +neotime-1.7.4 (defaults/linux-64)
    +notebook-6.0.3 (defaults/linux-64)
    +numpy-1.18.1 (defaults/linux-64)
    +numpy-base-1.18.1 (defaults/linux-64)
    +olefile-0.46 (defaults/linux-64)
    +openssl-1.1.1d (defaults/linux-64)
    +opt_einsum-3.1.0 (defaults/noarch)
    +packaging-20.1 (defaults/noarch)
    +pandas-1.0.1 (defaults/linux-64)
    +pandoc-2.2.3.2 (defaults/linux-64)
    +pandocfilters-1.4.2 (defaults/linux-64)
    +param-1.9.3 (defaults/noarch)
    +parso-0.6.1 (defaults/noarch)
    +pcre-8.43 (defaults/linux-64)
    +pexpect-4.8.0 (defaults/linux-64)
    +pickleshare-0.7.5 (defaults/linux-64)
    +pillow-7.0.0 (defaults/linux-64)
    +pip-20.0.2 (defaults/linux-64)
    +prometheus_client-0.7.1 (defaults/noarch)
    +prompt_toolkit-3.0.3 (defaults/noarch)
    +protobuf-3.11.2 (defaults/linux-64)
    +ptyprocess-0.6.0 (defaults/linux-64)
    +pycparser-2.19 (defaults/linux-64)
    +pyct-0.4.6 (defaults/linux-64)
    +pygments-2.5.2 (defaults/noarch)
    +pyopenssl-19.1.0 (defaults/linux-64)
    +pyparsing-2.4.6 (defaults/noarch)
    +pyqt-5.9.2 (defaults/linux-64)
    +pyrsistent-0.15.7 (defaults/linux-64)
    +pysocks-1.7.1 (defaults/linux-64)
    +python-3.7.6 (defaults/linux-64)
    +python-dateutil-2.8.1 (defaults/noarch)
    +pytz-2019.3 (defaults/noarch)
    +pyviz_comms-0.7.3 (defaults/noarch)
    +pyyaml-5.3 (defaults/linux-64)
    +pyzmq-18.1.1 (defaults/linux-64)
    +qt-5.9.7 (defaults/linux-64)
    +readline-7.0 (defaults/linux-64)
    +requests-2.22.0 (defaults/linux-64)
    +scikit-learn-0.22.1 (defaults/linux-64)
    +scipy-1.4.1 (defaults/linux-64)
    +send2trash-1.5.0 (defaults/linux-64)
    +setuptools-45.2.0 (defaults/linux-64)
    +sip-4.19.8 (defaults/linux-64)
    +six-1.14.0 (defaults/linux-64)
    +sqlite-3.31.1 (defaults/linux-64)
    +tensorboard-2.0.0 (defaults/noarch)
    +tensorflow-2.0.0 (defaults/linux-64)
    +tensorflow-base-2.0.0 (defaults/linux-64)
    +tensorflow-estimator-2.0.0 (defaults/noarch)
    +termcolor-1.1.0 (defaults/linux-64)
    +terminado-0.8.3 (defaults/linux-64)
    +testpath-0.4.4 (defaults/noarch)
    +tk-8.6.8 (defaults/linux-64)
    +toml-0.10.0 (defaults/linux-64)
    +toolz-0.10.0 (defaults/noarch)
    +tornado-6.0.3 (defaults/linux-64)
    +traitlets-4.3.3 (defaults/linux-64)
    +urllib3-1.25.8 (defaults/linux-64)
    +wcwidth-0.1.8 (defaults/noarch)
    +webencodings-0.5.1 (defaults/linux-64)
    +werkzeug-0.14.1 (defaults/linux-64)
    +wheel-0.34.2 (defaults/linux-64)
    +wrapt-1.11.2 (defaults/linux-64)
    +xz-5.2.4 (defaults/linux-64)
    +yaml-0.1.7 (defaults/linux-64)
    +zeromq-4.3.1 (defaults/linux-64)
    +zipp-2.2.0 (defaults/noarch)
    +zlib-1.2.11 (defaults/linux-64)
    +zstd-1.3.7 (defaults/linux-64)

2020-02-11 17:32:17  (rev 2)
    +flake8-3.7.9 (defaults/linux-64)
    +mccabe-0.6.1 (defaults/linux-64)
    +pycodestyle-2.5.0 (defaults/linux-64)
    +pyflakes-2.1.1 (defaults/linux-64)

2020-02-11 17:33:07  (rev 3)
     ca-certificates  {2020.1.1 (defaults/linux-64) -> 2019.11.28 (conda-forge/linux-64)}
     certifi  {2019.11.28 (defaults/linux-64) -> 2019.11.28 (conda-forge/linux-64)}
     openssl  {1.1.1d (defaults/linux-64) -> 1.1.1d (conda-forge/linux-64)}
    +aspy.yaml-1.3.0 (conda-forge/noarch)
    +cfgv-3.0.0 (conda-forge/noarch)
    +editdistance-0.5.3 (conda-forge/linux-64)
    +identify-1.4.11 (conda-forge/noarch)
    +jupytext-1.3.3 (conda-forge/noarch)
    +nodeenv-1.3.5 (conda-forge/noarch)
    +pre-commit-2.0.1 (conda-forge/linux-64)
    +virtualenv-16.7.5 (conda-forge/noarch)

2020-02-11 17:58:26  (rev 4)
     ca-certificates  {2019.11.28 (conda-forge/linux-64) -> 2020.1.1 (defaults/linux-64)}
     certifi  {2019.11.28 (conda-forge/linux-64) -> 2019.11.28 (defaults/linux-64)}
     openssl  {1.1.1d (conda-forge/linux-64) -> 1.1.1d (defaults/linux-64)}

2020-02-26 16:52:54  (rev 5)
    +arrow-cpp-0.15.1 (defaults/linux-64)
    +boost-cpp-1.71.0 (defaults/linux-64)
    +brotli-1.0.7 (defaults/linux-64)
    +bzip2-1.0.8 (defaults/linux-64)
    +double-conversion-3.1.5 (defaults/linux-64)
    +gflags-2.2.2 (defaults/linux-64)
    +glog-0.4.0 (defaults/linux-64)
    +grpc-cpp-1.26.0 (defaults/linux-64)
    +libboost-1.71.0 (defaults/linux-64)
    +libevent-2.1.8 (defaults/linux-64)
    +lz4-c-1.8.1.2 (defaults/linux-64)
    +pyarrow-0.15.1 (defaults/linux-64)
    +re2-2019.08.01 (defaults/linux-64)
    +snappy-1.1.7 (defaults/linux-64)
    +thrift-cpp-0.11.0 (defaults/linux-64)
    +uriparser-0.9.3 (defaults/linux-64)

2020-02-26 16:54:07  (rev 6)
     ca-certificates  {2020.1.1 (defaults/linux-64) -> 2019.11.28 (conda-forge/linux-64)}
     certifi  {2019.11.28 (defaults/linux-64) -> 2019.11.28 (conda-forge/linux-64)}
     openssl  {1.1.1d (defaults/linux-64) -> 1.1.1d (conda-forge/linux-64)}
    +arrow-0.15.5 (conda-forge/linux-64)
    +binaryornot-0.4.4 (conda-forge/noarch)
    +cookiecutter-1.7.0 (conda-forge/noarch)
    +future-0.18.2 (conda-forge/linux-64)
    +jinja2-time-0.2.0 (conda-forge/noarch)
    +poyo-0.5.0 (conda-forge/noarch)
    +whichcraft-0.6.1 (conda-forge/noarch)

2020-02-26 16:54:26  (rev 7)
     ca-certificates  {2019.11.28 (conda-forge/linux-64) -> 2020.1.1 (defaults/linux-64)}
     certifi  {2019.11.28 (conda-forge/linux-64) -> 2019.11.28 (defaults/linux-64)}
     openssl  {1.1.1d (conda-forge/linux-64) -> 1.1.1d (defaults/linux-64)}
    +xlrd-1.2.0 (defaults/linux-64)

2020-02-26 16:55:12  (rev 8)
     ca-certificates  {2020.1.1 (defaults/linux-64) -> 2019.11.28 (conda-forge/linux-64)}
     certifi  {2019.11.28 (defaults/linux-64) -> 2019.11.28 (conda-forge/linux-64)}
     openssl  {1.1.1d (defaults/linux-64) -> 1.1.1d (conda-forge/linux-64)}
    +anyconfig-0.9.10 (conda-forge/noarch)

2020-02-26 16:55:45  (rev 9)
     ca-certificates  {2019.11.28 (conda-forge/linux-64) -> 2020.1.1 (defaults/linux-64)}
     certifi  {2019.11.28 (conda-forge/linux-64) -> 2019.11.28 (defaults/linux-64)}
     openssl  {1.1.1d (conda-forge/linux-64) -> 1.1.1d (defaults/linux-64)}
    +fsspec-0.6.2 (defaults/noarch)

2020-02-26 16:56:06  (rev 10)
     ca-certificates  {2020.1.1 (defaults/linux-64) -> 2019.11.28 (conda-forge/linux-64)}
     certifi  {2019.11.28 (defaults/linux-64) -> 2019.11.28 (conda-forge/linux-64)}
     openssl  {1.1.1d (defaults/linux-64) -> 1.1.1d (conda-forge/linux-64)}
    +python-json-logger-0.1.11 (conda-forge/noarch)

2020-02-26 16:56:30  (rev 11)
     ca-certificates  {2019.11.28 (conda-forge/linux-64) -> 2020.1.1 (defaults/linux-64)}
     certifi  {2019.11.28 (conda-forge/linux-64) -> 2019.11.28 (defaults/linux-64)}
     openssl  {1.1.1d (conda-forge/linux-64) -> 1.1.1d (defaults/linux-64)}
    +boto3-1.12.0 (defaults/noarch)
    +botocore-1.15.0 (defaults/noarch)
    +docutils-0.15.2 (defaults/linux-64)
    +jmespath-0.9.4 (defaults/noarch)
    +s3fs-0.4.0 (defaults/noarch)
    +s3transfer-0.3.3 (defaults/linux-64)

2020-02-26 16:56:42  (rev 12)
    +sqlalchemy-1.3.13 (defaults/linux-64)

2020-02-26 16:57:40  (rev 13)
    +blosc-1.16.3 (defaults/linux-64)
    +lzo-2.10 (defaults/linux-64)
    +mock-4.0.1 (defaults/noarch)
    +numexpr-2.7.1 (defaults/linux-64)
    +pytables-3.6.1 (defaults/linux-64)

2020-02-26 16:57:54  (rev 14)
    +llvmlite-0.31.0 (defaults/linux-64)
    +numba-0.48.0 (defaults/linux-64)
    +tbb-2020.0 (defaults/linux-64)

2020-02-26 16:58:15  (rev 15)
     ca-certificates  {2020.1.1 (defaults/linux-64) -> 2019.11.28 (conda-forge/linux-64)}
     certifi  {2019.11.28 (defaults/linux-64) -> 2019.11.28 (conda-forge/linux-64)}
     openssl  {1.1.1d (defaults/linux-64) -> 1.1.1d (conda-forge/linux-64)}
    +toposort-1.5 (conda-forge/noarch)

2020-02-26 16:58:29  (rev 16)
     ca-certificates  {2019.11.28 (conda-forge/linux-64) -> 2020.1.1 (anaconda/linux-64)}
     certifi  {2019.11.28 (conda-forge/linux-64) -> 2019.11.28 (anaconda/linux-64)}
     openssl  {1.1.1d (conda-forge/linux-64) -> 1.1.1 (anaconda/linux-64)}
     requests  {2.22.0 (defaults/linux-64) -> 2.22.0 (anaconda/linux-64)}

2020-02-26 16:59:19  (rev 17)
     ca-certificates  {2020.1.1 (anaconda/linux-64) -> 2019.11.28 (conda-forge/linux-64)}
     certifi  {2019.11.28 (anaconda/linux-64) -> 2019.11.28 (conda-forge/linux-64)}
     openssl  {1.1.1 (anaconda/linux-64) -> 1.1.1d (conda-forge/linux-64)}
    +alembic-1.4.0 (conda-forge/noarch)
    +backports-1.0 (conda-forge/noarch)
    +cloudpickle-1.3.0 (conda-forge/noarch)
    +configparser-3.7.3 (conda-forge/linux-64)
    +databricks-cli-0.9.1 (conda-forge/noarch)
    +docker-py-4.2.0 (conda-forge/linux-64)
    +docker-pycreds-0.4.0 (conda-forge/noarch)
    +flask-1.1.1 (conda-forge/noarch)
    +gitdb-4.0.2 (conda-forge/noarch)
    +gitpython-3.1.0 (conda-forge/noarch)
    +gorilla-0.3.0 (conda-forge/noarch)
    +gunicorn-20.0.4 (conda-forge/linux-64)
    +itsdangerous-1.1.0 (conda-forge/noarch)
    +mako-1.1.0 (conda-forge/noarch)
    +mlflow-1.6.0 (conda-forge/linux-64)
    +prometheus_flask_exporter-0.12.2 (conda-forge/noarch)
    +python-editor-1.0.4 (conda-forge/noarch)
    +querystring_parser-1.2.4 (conda-forge/noarch)
    +simplejson-3.17.0 (conda-forge/linux-64)
    +smmap-3.0.1 (conda-forge/noarch)
    +sqlparse-0.3.0 (conda-forge/noarch)
    +tabulate-0.8.6 (conda-forge/noarch)
    +websocket-client-0.57.0 (conda-forge/linux-64)

2020-02-26 17:01:48  (rev 18)
     ca-certificates  {2019.11.28 (conda-forge/linux-64) -> 2020.1.1 (defaults/linux-64)}
     certifi  {2019.11.28 (conda-forge/linux-64) -> 2019.11.28 (defaults/linux-64)}
     openssl  {1.1.1d (conda-forge/linux-64) -> 1.1.1d (defaults/linux-64)}

2020-02-26 19:06:56  (rev 19)
     ca-certificates  {2020.1.1 (defaults/linux-64) -> 2019.11.28 (conda-forge/linux-64)}
     certifi  {2019.11.28 (defaults/linux-64) -> 2019.11.28 (conda-forge/linux-64)}
     openssl  {1.1.1d (defaults/linux-64) -> 1.1.1d (conda-forge/linux-64)}
    +cached-property-1.5.1 (conda-forge/noarch)
    +pre_commit-1.18.1 (conda-forge/linux-64)

2020-02-26 19:11:00  (rev 20)
     ca-certificates  {2019.11.28 (conda-forge/linux-64) -> 2020.1.1 (defaults/linux-64)}
     certifi  {2019.11.28 (conda-forge/linux-64) -> 2019.11.28 (defaults/linux-64)}
     openssl  {1.1.1d (conda-forge/linux-64) -> 1.1.1d (defaults/linux-64)}
     werkzeug  {0.14.1 (defaults/linux-64) -> 0.15.4 (defaults/noarch)}

2020-02-26 20:00:27  (rev 21)
     backports  {1.0 (conda-forge/noarch) -> 1.0 (defaults/noarch)}
     cached-property  {1.5.1 (conda-forge/noarch) -> 1.5.1 (defaults/noarch)}
     cloudpickle  {1.3.0 (conda-forge/noarch) -> 1.3.0 (defaults/noarch)}
     docker-pycreds  {0.4.0 (conda-forge/noarch) -> 0.4.0 (defaults/noarch)}
     flask  {1.1.1 (conda-forge/noarch) -> 1.1.1 (defaults/noarch)}
     future  {0.18.2 (conda-forge/linux-64) -> 0.18.2 (defaults/linux-64)}
     gunicorn  {20.0.4 (conda-forge/linux-64) -> 20.0.4 (defaults/linux-64)}
     itsdangerous  {1.1.0 (conda-forge/noarch) -> 1.1.0 (defaults/noarch)}
     python-editor  {1.0.4 (conda-forge/noarch) -> 1.0.4 (defaults/noarch)}
     requests  {2.22.0 (anaconda/linux-64) -> 2.22.0 (defaults/linux-64)}
     sqlparse  {0.3.0 (conda-forge/noarch) -> 0.3.0 (defaults/noarch)}
     virtualenv  {16.7.5 (conda-forge/noarch) -> 16.7.5 (defaults/noarch)}

2020-02-26 20:22:17  (rev 22)
     ca-certificates  {2020.1.1 (defaults/linux-64) -> 2019.11.28 (conda-forge/linux-64)}
     certifi  {2019.11.28 (defaults/linux-64) -> 2019.11.28 (conda-forge/linux-64)}
     openssl  {1.1.1d (defaults/linux-64) -> 1.1.1d (conda-forge/linux-64)}
     pandas  {1.0.1 (defaults/linux-64) -> 1.0.1 (conda-forge/linux-64)}
    -pytables-3.6.1 (defaults/linux-64)
    +google-cloud-sdk-281.0.0 (conda-forge/linux-64)

2020-02-26 20:48:13  (rev 23)
     pandas  {1.0.1 (conda-forge/linux-64) -> 1.0.1 (defaults/linux-64)}
    +cachetools-3.1.1 (conda-forge/noarch)
    +google-api-core-1.16.0 (conda-forge/linux-64)
    +google-auth-1.11.2 (conda-forge/noarch)
    +google-cloud-core-1.3.0 (conda-forge/noarch)
    +googleapis-common-protos-1.51.0 (conda-forge/linux-64)
    +pyasn1-0.4.8 (conda-forge/noarch)
    +pyasn1-modules-0.2.7 (conda-forge/noarch)
    +rsa-4.0 (conda-forge/noarch)

2020-02-26 20:49:49  (rev 24)
    +fastavro-0.22.10 (conda-forge/linux-64)
    +google-api-core-grpc-1.16.0 (conda-forge/linux-64)
    +google-cloud-bigquery-1.24.0 (conda-forge/noarch)
    +google-cloud-bigquery-core-1.24.0 (conda-forge/linux-64)
    +google-cloud-bigquery-storage-0.7.0 (conda-forge/noarch)
    +google-cloud-bigquery-storage-core-0.7.0 (conda-forge/linux-64)
    +google-resumable-media-0.5.0 (conda-forge/noarch)
    +tqdm-4.43.0 (conda-forge/noarch)

2020-03-09 15:47:01  (rev 25)
     ca-certificates  {2019.11.28 (conda-forge/linux-64) -> 2020.1.1 (defaults/linux-64)}
     certifi  {2019.11.28 (conda-forge/linux-64) -> 2019.11.28 (defaults/linux-64)}
     openssl  {1.1.1d (conda-forge/linux-64) -> 1.1.1d (defaults/linux-64)}
    +pysal-1.14.4.post1 (defaults/linux-64)
